requirements-dev.txt, setup.py, stactask/task.py, tests/fixtures/sentinel2-items.json, tests/test_task.py
In the process of using the STAC Task class, I encountered some issues that I think these commits address, and would benefit anyone using this.  Curious what @matthewhanson thinks about number 5.
1. If this moves to stactools, maybe the added requirements would already be present.
2. Tests updated, and now all pass.
3. dangling references to `output_options` removed
4. tried to keep `python-black` from changing every line.
5. Dropped the `return output` from the `Task.cli`, since this blows up the terminal with the `_item_collection`.
=> update tests and some suggested changes

setup.py
That module doesn't exist so it was just an error.
=> Remove console_scripts

.pre-commit-config.yaml, MANIFEST.in, pyproject.toml, stactask/asset_io.py, stactask/task.py, stactask/utils.py, tests/tasks.py
Includes:
- autoupdate to pre-commit hooks
- switch mypy to strict mode
- typing fixes
- `py.typed` file, for downstreams
- some formatting fixes
=> Fix typing

CHANGELOG.md, stactask/task.py, tests/test_task.py
I ran into some issues with workdir not being absolute, specifically with stac-asset trying to download remote assets for an item with some local assets with hrefs based on the workdir and therefore non-absolute paths. Forcing the workdir path to be absolute works around this issue.
I think this change also helps in the case where processing code changes the working directory for some reason. As relative paths are interpreted relative to the cwd, changing the cwd could cause really bad things to happen if the workdir path is not absolute.
=> Ensure workdir is always an absolute path

stactask/task.py, tests/tasks.py, tests/test_task.py
Closes #35 
I figure the tasks themselves need to tell us why the payload is invalid, but this does require tasks to re-write their validate methods.
=> Give more informative validation errors

.pre-commit-config.yaml, CHANGELOG.md, stactask/task.py, tests/test_task.py
This handles a few issues with the existing workdir cleanup:
1) Only doing this in __del__ did not guarantee it would ever be called, as Python does not guarantee `__del__` is called before the interpreter exists (see https://docs.python.org/3/reference/datamodel.html#object.__del__ , "It is not guaranteed that __del__() methods are called for objects that still exist when the interpreter exits.")
2) __del__ can be called in __init__, which would throw an exception because _workdir would be undefined.
Changes:
1) handler now explicitly calls workdir_cleanup
2) workdir_cleanup is correctly defensive and logs errors
3) __del__ will never throw a cleanup exception (not very relevant now, but important if additional `__del__` operations are added in the future.
=> cleanup workdir correctly

CHANGELOG.md, stactask/asset_io.py, tests/test_task_download.py
In particular, it can happen that a stac-task is copying between file systems using the LocalFileSystem implementation, and that doesn't provide the async interface.
=> add support for non-async filesystems

.gitignore, CHANGELOG.md, stactask/asset_io.py, stactask/task.py, tests/test_task.py, tests/test_task_download.py
=> keep original filenames

CHANGELOG.md, stactask/asset_io.py
Easy fix, which I'm including prep for a bugfix release 0.4.1.
=> don't transform hrefs when making a copy

CHANGELOG.md, pyproject.toml, stactask/asset_io.py, stactask/task.py
Task.upload_item_assets_to_s3 and asset_io.upload_item_assets_to_s3 support explicitly specifying the boto3utils3.s3 object
This allows greater flexibility in setting various AWS S3 parameters, which allows this to support S3-compatible APIs like MinIO.
=> Support explicitly specifying the boto3utils3.s3 object

CHANGELOG.md, stactask/task.py, tests/fixtures/sentinel2-l2a-j2k-payload.json, tests/test_task.py
- https://github.com/stac-utils/stac-task/issues/58
This PR stops adding the processing:software attribute to Items, as this is intended to be the data processing software, and the stactask is most frequently used for metadata processing.
=> don't add processing:software to items automatically

CHANGELOG.md, README.md, stactask/task.py, tests/test_task.py
- `--local` flag no longer turns off validation https://github.com/stac-utils/stac-task/issues/103
- CLI flags `--skip-upload` and `--skip-validation` deprecated in favor of `--upload/--no-upload` and `--validate/no-validate`. This makes use a more standard CLI scheme, makes them positive by default, and makes them both verbs (rather than upload being a verb and validation being a noun)
=> replace skip-upload and skip-validation with validate/no-validate and upload/no-upload

stactask/asset_io.py
Currently `stack-task` encounters issues with presigned URLs, resulting in the following error when attempting to create a file with a name that includes the part after the `?` symbol:
```
OSError: [Errno 36] File name too long
```
```
>>> href = "http://foo.bar/raster.tif?x-user=no-user-in-request&X-Amz-Algorithm="
>>> basename = os.path.basename(href)
>>> new_href = os.path.join("", basename)
>>> new_href
'raster.tif?x-user=no-user-in-request&X-Amz-Algorithm='
```
This pull request aims to resolve this issue.
=> Refactor file name extraction using urlparse

docs/source/usage.rst, stactask/task.py
To enable pipelines from the CLI:
```
stac-client $params | python3 task.py run | python3 task2.py run
```
=> stdin/stdout handling for CLI

CHANGELOG.md, stactask/task.py, stactask/utils.py, tests/test_task.py, tests/test_utils.py
Add utility method and property for allowing the collection for a newly-created Item to be retrieved. This is useful if you need to know which collection the Item will go into prior to returning it from process. One use of this is when data is created an uploaded as part of the task, and you want the data to be uploaded to a path like `{collection}/{id}`, so you need to know the collection within the process method, instead of only having it set in the Item in post_process.
- https://github.com/stac-utils/stac-task/issues/109
=> add collection mapping methods

.github/workflows/continuous-integration.yml, CHANGELOG.md, pyproject.toml
- n/a
1. Python 3.8 is EOL this year, so there are no new projects that should be using it, and existing projects don't need to update to the next major-minor.
2. In the last two changes I've tried to make, I've had incompatibilities with 3.8 that have required a workaround, so supporting it is becoming a burden.
=> remove support for Python 3.8

.github/workflows/continuous-integration.yml, CHANGELOG.md, pyproject.toml, stactask/task.py, tests/fixtures/sentinel2-l2a-j2k-payload.json, tests/test_task.py
- https://github.com/stac-utils/stac-task/issues/108
1. Add upload_local_item_assets_to_s3 method that uploads all local items (in workdir) to S3.
=> add Task.upload_local_item_assets_to_s3 method

stactask/logging.py
- n/a
1. add correct typing to the logger after removing 3.8 (since the typing wouldn't work with 3.8)
=> add correct typing to the logger after removing 3.8

CHANGELOG.md, README.md, pyproject.toml, stactask/__init__.py, stactask/asset_io.py, stactask/config.py, stactask/task.py, tests/test_task_download.py
- https://github.com/stac-utils/stac-task/issues/76
1. Replace uses of fsspec for downloading with stac-asset
=> replace use of fsspec for downloading Item Assets with stac-asset

CHANGELOG.md, stactask/asset_io.py, stactask/task.py
- [stac-utils/stac-task/issues/128](https://github.com/stac-utils/stac-task/issues/128)
I encountered a need to store an item with the name derived from its ID.
The name of the item file to save can now be configured. If the `file_name` argument is not provided, `item.json` will be used (current behavior). If `file_name` is explicitly set to `None`, the file name will be inferred from the item’s ID, leveraging the `stac-asset` library (see `infer_file_name` parameter definition in the [stac-asset documentation](https://stac-asset.readthedocs.io/en/latest/api.html#stac_asset.blocking.download_item)).
=> Configure the filename for saving the item

CHANGELOG.md, README.md, docs/source/conf.py, pyproject.toml
=> Release prep v0.6.0

CHANGELOG.md, README.md, stactask/task.py, tests/fixtures/sentinel2-l2a-j2k-payload.json, tests/test_task.py
- #123 
1. Accept a list of process definition dictionaries. 
2. And continue to accept a bare dictionary for the process definition, but emit a Deprecation warning.
3. Some decent massaging of the README.
=> 123: Support `process` arrays

CHANGELOG.md, README.md, stactask/task.py, tests/test_task.py
- #165 
1. Adds a `workflow_options` dictionary of workflow-level options to the `ProcessDefinition` object. These options are combined with the options of each task in the workflow. If there is a conflict (same dictionary key), the task option value takes precedence.
2. Adds a `workflow_options` property to the `Task` class that returns the `workflow_options` dictionary from the `ProcessDefinition` object.
3. Adds a `task_options` property to the `Task` class that returns the task options from the `tasks` dictionary in the `ProcessDefinition` object.
=> 165: Add workflow-level option support

CHANGELOG.md, README.md, docs/source/usage.rst
- None
1. Updates changelog.
2. Minor docs corrections.
=> Release prep for v0.7.0

.github/workflows/continuous-integration.yml, .github/workflows/release.yml, pyproject.toml
- None
1. Trigger full test suite run and docs build on release tag (tag that starts with `v`) push to main branch.
2. Only build and push release to pypi for tags that start with `v`.
3. Add Documentation link to pyproject.yaml (exposed on pypi)
=> Trigger docs build on release tag push to main
